### ISSUE TITLE
Export/Import resources and folders

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-server#17]
There is no easy way to import a big number of resources.

**Comment by marcosmro** [comment]
We just had a short discussion about this task and concluded that we should try to address it soon. We will talk about the priority of this task when @martinjoconnor is back.

**Comment by martinjoconnor** [comment]
Will prove useful for versioning work.

**Comment by martinjoconnor** [comment]
Possible follow on task to do system backups: 

https://github.com/metadatacenter/cedar-project/issues/69
