### ISSUE TITLE
REST Resource Validation Endpoints

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-server#5]
Currently template, element, and field instances are not validated by the REST API.

**Comment by martinjoconnor** [comment]
Related to #4.

**Comment by martinjoconnor** [comment]
Verify conformance to model changes in  metatadatacenter/cedar-template-editor#491

**Comment by martinjoconnor** [comment]
Moved out of 0.8 release because we do not trust to overreport issues. Will finalize in concert with remaining metadatacenter/cedar-template-editor#491 tasks.

**Comment by martinjoconnor** [comment]
Need to now also consider the proposed workflow state field (metadatacenter/cedar-template-editor#38).

**Comment by martinjoconnor** [comment]
Validation library now completed (https://github.com/metadatacenter/cedar-model-validation-library) but not yet hooked up at REST level.

**Comment by martinjoconnor** [comment]
Create REST endpoints on template server as follows:

/commands/validate/template
/commands/validate/template-element
/commands/validate/template-field
/commands/validate/template-instance
/commands/validate/template-element-instance
/commands/validate/template-field-instance

Return JSON of form:

{
  "validates": true,
  "errors": [ "mess1", "mess2" ],
  "warnings": [ "mess1", "mess2" ]
}

**Comment by johardi** [comment]
We won't be able to create the last two endpoints until we have a standalone element instances and field instances.
