### ISSUE TITLE
Server error on field name with .. (2 dots) or other invalid content

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-server#9]
add text field and name it with .. (maybe one dot?)

**Comment by martinjoconnor** [comment]
Need to do front end validation to ensure that field names will not be invalid or map them to valid identifiers.

The server side validation task (#5) will also do validation but it would be good to head this one immediately.

**Comment by martinjoconnor** [comment]
Merged into #491.

**Comment by martinjoconnor** [comment]
Previously merged into metadatacenter/cedar-template-editor#318.

**Comment by martinjoconnor** [comment]
Model validation now catches (metadatacenter/cedar-model-validation-library#23).
